### ISSUE TITLE
devon.exe failed

### ISSUE THREAD

**Issue by LennyPenny** [j1and1/Virtual-Audio-Pipeline#1]
Running Install.bat on windows 10 admin cmd gives me this: 
```C:\Users\Lenny\Documents\stuffs\audiorouter\vaudio pipeline>Install.bat
Device node created. Install is complete when drivers are installed...
Updating drivers for *SONICSWaveExtensible from C:\Users\Lenny\Documents\stuffs\audiorouter\vaudio pipeline\vrtaupipe.inf.
devcon.exe failed.
```

**Comment by j1and1** [comment]
@LennyPenny 

Could you please try installing it again and provide me with log from `setupapi.dev.log` witch is located at `C:\Windows\inf` ?

Oh and did you turn off driver signature validation for Windows as the driver is not signed?

**Comment by LennyPenny** [comment]
Oh I guess driver signature validation was the problem then. 
Unfortunately I don't really wanna turn that off since some anti cheats in video games will prevent me from playing then
